#' Area under the concentration versus time cruve from time 0 until the last time point
#'
#' This function gets the area under the concentration versus time curve from time 0 until the last
#' time point. As illustrated in the following figure, AUC_ALL includes the trapezoidal area from the 
#' time of the last measurable concentration to the next time point. Although there may be additional
#' time points, there is no additonal AUC since by defination all subsequent concentrations are zero.\cr
#' \figure{auc_all.png}
#' 
#' @details
#' \strong{Linear Method} \cr  
#' \figure{auc_1.png} \cr
#' \strong{Log Method} \cr  
#' \figure{auc_2.png} \cr
#' \eqn{AUC = Area under the cruve} \cr
#' \eqn{C_{i} = Concentration 1}{Ci = Concentration 1} \cr
#' \eqn{C_{i+1} = Concentration 2}{Ci+1 = Concentration 2} \cr
#' \eqn{T_{i} = Time 1}{Ti = Time 1} \cr
#' \eqn{T_{i+1} = Time 2}{Ti+1 = Time 2} \cr
#' \eqn{ln = Natural Logarithm} \cr \cr
#' \strong{Methods:} You can use the following methods to calculate AUC: \cr
#' \enumerate{
#'  \item \strong{Linear-Log Trapazoidal Rule}(default method): The linear method is used up to Tmax (the 
#'  first occurance of Cmax) and the log trapezoidal method is used for the remainder of the profile. If
#'  Ci or Ci+1 is 0 then the linear trapezoidal rule is used.
#'  \item \strong{Linear Trapazoidal Rule}: The linear method is used for the entire profile.
#'  \item \strong{Log Trapazoidal Rule}: The log trapezoidal method is used for the entire profile. If
#'  Ci or Ci+1 is 0 then the linear trapezoidal rule is used.
#'  \item \strong{Linear Up - Log Down Trapazoidal Rule}: Linear trapezoidal while the concentrations
#'  are increasing and log trapezoidal while the concentration are decreasing, the assessment is made on
#'  a step basis for each portion of the profile i.e. t1 to t2. If Ci or Ci+1 is 0 then the linear 
#'  trapezoidal rule is used.
#' }
#' \strong{Equation} \cr
#' If the user selects the option to have dose normalized AUC then the following equation is applied: \cr 
#' \figure{auc_dn.png} \cr 
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @param method The method that will be used to calculate AUC (use either 1, 2, 3, or 4)\cr
#' \enumerate{
#' \item Linear-Log Trapazoidal Rule (default)
#' \item Linear Trapazoidal Rule 
#' \item Log Trapazoidal Rule 
#' \item Linear Up - Log DownTrapazoidal Rule 
#' } 
#' Note: check 'Methods' section below for more details \cr
#' @param dose_normalize The option to dose normalize the AUC (default is 'FALSE')
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item AUC: area under the curve
#'  \item METHOD: method used to calculate AUC
#'  \item DOSE_NORM: whether the AUC represented is dose normalized
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' auc_all()   
#' #No data found!
#' 
#' auc_all(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' auc_all(mod)  
#' #Please specify for which subject you want to get the AUC_ALL for!
#' 
#' auc_all(mod, sid = "all") 
#' #  SID              AUC     METHOD
#' #   30 4.94993257703106 Linear-Log
#' #   31                1 Linear-Log
#' #   32 5.15416479501756 Linear-Log
#' 
#' auc_all(mod, sid = 32)  
#' #  SID              AUC     METHOD
#' #   32 5.15416479501756 Linear-Log
#' 
#' auc_all(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' auc_all(mod, sid = 31, method = 5)
#' #Invalid method number! Please provide a valid value for method!
#' 
#' @author
#' \itemize{
#'  \item Ronish Desai: \email{rbdesai@@rudraya.com} 
#' }
#' Other contributors: \cr
#' \itemize{
#'  \item Rudraya Corporation: \url{http://rudraya.com}
#' }
#' \figure{rudraya.png} 
#' @export
auc_lin_log <- function(conc = NULL, time = NULL){
  if(is.null(conc) && is.null(time)){
    stop("Error in auc_lin_log: 'conc' and 'time' vectors are NULL")
  } else if(is.null(conc)) {
    stop("Error in auc_lin_log: 'conc' vector is NULL")
  } else if(is.null(time)) {
    stop("Error in auc_lin_log: 'time' vectors is NULL")
  }
  
  if(!(is.numeric(conc) && is.vector(conc)) ){
    stop("Error in auc_lin_log: 'conc' is not a numeric vector")
  }
  if(!(is.numeric(time) && is.vector(time)) ){
    stop("Error in auc_lin_log: 'time' is not a numeric vector")
  }
  if(length(time) != length(conc) ){
    stop("Error in auc_lin_log: length of 'time' and 'conc' vectors are not equal")
  }
  
  #Formatting data to remove any NA or less than 0 concentration values and corresponding time values 
  time <- time[!is.na(conc)]
  conc <- conc[!is.na(conc)]
  
  tmp <- data.frame(time, conc)
  if(nrow(tmp) < 2){
    auc <- NA
    return(auc)
  } else {
    t_max <- tmax(conc = conc, time = time)
    auc_df <- ""
    
    if(!is.na(t_max)){
      for(i in 1:(nrow(tmp)-1)){
        if(i+1 <= t_max){
          auc_df[i] <- ((tmp$conc[i] + tmp$conc[i+1])/2)*(tmp$time[i+1]-tmp$time[i])    
        } else {
          if(tmp$conc[i] == 0 || tmp$conc[i+1] == 0){
            auc_df[i] <- ((tmp$conc[i] + tmp$conc[i+1])/2)*(tmp$time[i+1]-tmp$time[i])
          } else {
            tmp_ln <- tmp$conc[i]/tmp$conc[i+1]
            #print(paste0("tmp_ln:", tmp_ln))
            auc_df[i] <- ((tmp$conc[i] - tmp$conc[i+1])/log(tmp_ln))*(tmp$time[i+1]-tmp$time[i])
          }
        }
      }
    } else {
      stop("Error in auc_lin_log: 'tmax' is NA")
    }
    auc_df <- as.numeric(auc_df)
    auc <- sum(auc_df, na.rm = TRUE)
  }
  return(auc)
}