#' Area under the first moment curve
#'
#' This function gets the area under the area under the curve from zero time until the last
#' measurable concentration is calculated using the trapezoidal rule
#' 
#' @details
#' \strong{Linear Method} \cr  
#' \figure{aumc_1.png} \cr
#' \strong{Log Method} \cr  
#' \figure{aumc_2.png} \cr
#' \eqn{AUMC = Area under the first moment curve} \cr
#' \eqn{C_{i} = Concentration 1}{Ci = Concentration 1} \cr
#' \eqn{C_{i+1} = Concentration 2}{Ci+1 = Concentration 2} \cr
#' \eqn{T_{i} = Time 1}{Ti = Time 1} \cr
#' \eqn{T_{i+1} = Time 2}{Ti+1 = Time 2} \cr
#' \eqn{ln = Natural Logarithm} \cr \cr
#' \strong{Methods:} You can use the following methods to calculate AUC: \cr
#' \enumerate{
#'  \item \strong{Linear-Log Trapazoidal Rule}(default method): The linear method is used up to Tmax (the 
#'  first occurance of Cmax) and the log trapezoidal method is used for the remainder of the profile. If
#'  Ci or Ci+1 is 0 then the linear trapezoidal rule is used.
#'  \item \strong{Linear Trapazoidal Rule}: The linear method is used for the entire profile.
#'  \item \strong{Log Trapazoidal Rule}: The log trapezoidal method is used for the entire profile. If
#'  Ci or Ci+1 is 0 then the linear trapezoidal rule is used.
#'  \item \strong{Linear Up - Log Down Trapazoidal Rule}: Linear trapezoidal while the concentrations
#'  are increasing and log trapezoidal while the concentration are decreasing, the assessment is made on
#'  a step basis for each portion of the profile i.e. t1 to t2. If Ci or Ci+1 is 0 then the linear 
#'  trapezoidal rule is used.
#' }
#' \strong{Equation} \cr
#' If the user selects the option to have dose normalized AUC then the following equation is applied: \cr 
#' \figure{auc_dn.png} \cr 
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @param method The method that will be used to calculate AUC (use either 1, 2, 3, or 4)\cr
#' \enumerate{
#' \item Linear-Log Trapazoidal Rule (default)
#' \item Linear Trapazoidal Rule 
#' \item Log Trapazoidal Rule 
#' \item Linear Up - Log DownTrapazoidal Rule 
#' } 
#' Note: check 'Methods' section below for more details \cr
#' @param dose_normalize The option to dose normalize the AUC (default is 'FALSE')
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item AUMC: area under the first moment curve until time of last mesurable concentration 
#'  \item METHOD: method used to calculate AUC
#'  \item DOSE_NORM: whether the AUC represented is dose normalized
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' aumc_last()   
#' #No data found!
#' 
#' aumc_last(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' aumc_last(mod)  
#' #Please specify for which subject you want to get the AUMC_LAST for!
#' 
#' aumc_last(mod, sid = "all")  
#' #Please specify for which end time you want to get the AUMC_LAST for!
#' 
#' aumc_last(mod, sid = "all") 
#' #  SID              AUC     METHOD 
#' #   30 4.94993257703106 Linear-Log
#' #   31              0.5 Linear-Log
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_last(mod, sid = 32)  
#' #  SID              AUC     METHOD
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_last(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' aumc_last(mod, sid = 31)  
#' #Invalid time input! Time not found in the data provided!
#' 
#' aumc_last(mod, sid = 31, method = 5)
#' #Invalid method number! Please provide a valid value for method!
#' 
#' @author
#' \itemize{
#'  \item Ronish Desai: \email{rbdesai@@rudraya.com} 
#' }
#' Other contributors: \cr
#' \itemize{
#'  \item Rudraya Corporation: \url{http://rudraya.com}
#' }
#' \figure{rudraya.png} 
#' @export
aumc_last <- function(conc = NULL, time = NULL, method = 1){
  if(is.null(conc) && is.null(time)){
    stop("Error in aumc_last: 'conc' and 'time' vectors are NULL")
  } else if(is.null(conc)) {
    stop("Error in aumc_last: 'conc' vector is NULL")
  } else if(is.null(time)) {
    stop("Error in aumc_last: 'time' vectors is NULL")
  }
  
  if(!(is.numeric(conc) && is.vector(conc)) ){
    stop("Error in aumc_last: 'conc' is not a numeric vector")
  }
  if(!(is.numeric(time) && is.vector(time)) ){
    stop("Error in aumc_last: 'time' is not a numeric vector")
  }
  if(method != 1 && method != 2 && method != 3 && method != 4){
    stop("Error in aumc_last: the value provided for 'method' is not correct")
  }
  
  #Formatting data to subset data based on time values
  t_last <- tlast(conc = conc, time = time)
  conc <- conc[time <= t_last]
  time <- time[time <= t_last]
  
  if(length(time) != length(conc)){
    stop("Error in aumc_last: length of 'time' and 'conc' vectors are not equal")
  }
  
  if(method == 1){
    return(aumc_lin_log(conc = conc, time = time))
  } else if(method == 2){
    return(aumc_lin(conc = conc, time = time))
  } else if(method == 3){
    return(aumc_log(conc = conc, time = time))
  } else if(method == 4){
    return(aumc_lin_up_log_down(conc = conc, time = time))
  }
}
