#' Volume of distribution (observed) based on the terminal phase.
#' 
#' @details
#' \strong{Model M2 and M3}
#' Single Dose Equation only not calculated at steady-state (only VZ/P is calculated using AUCTAU as the correct PK variable)
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{vzo.png} \cr
#'  }
#' }
#' \eqn{F = fraction of dose absorbed [is assumed to be 1]} \cr  
#' \eqn{KEL = Terminal or elimination phase rate constant.} \cr
#' \eqn{AUCINFO = Area under the first moment curve from zero time to infinity (Observed)} \cr  
#' \eqn{Dosei = dose value for drug dosing interval i} \cr   
#'
#' @section Additional Details:
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @param method The method that will be used to calculate AUC (use either 1, 2, 3, or 4)\cr
#' 
#' \enumerate{
#' \item Linear-Log Trapazoidal Rule (default)
#' \item Linear Trapazoidal Rule 
#' \item Log Trapazoidal Rule 
#' \item Linear Up - Log DownTrapazoidal Rule 
#' } 
#' Note: check 'Methods' section below for more details \cr
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item AUMC_PER: percentage of area under the curve
#'  \item METHOD: method used to calculate AUC
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' aumc_XpctP()   
#' #No data found!
#' 
#' aumc_XpctP(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' aumc_XpctP(mod)  
#' #Please specify for which subject you want to get the AUMC_XPCTP for!
#' 
#' aumc_XpctP(mod, sid = "all") 
#' #  SID              AUC     METHOD
#' #   30 4.94993257703106 Linear-Log
#' #   31                1 Linear-Log
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 32)  
#' #  SID              AUC     METHOD
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' aumc_XpctP(mod, sid = 31, method = 5)
#' #Invalid method number! Please provide a valid value for method!
#' 
#' @author
#' \itemize{
#'  \item Ronish Desai: \email{rbdesai@@rudraya.com} 
#' }
#' Other contributors: \cr
#' \itemize{
#'  \item Rudraya Corporation: \url{http://rudraya.com}
#' }
#' \figure{rudraya.png} 
#' @export
cav <- function(auctau = NULL, tau = NULL){
  if(is.null(auctau) && is.null(tau)){
    stop("Error in vzo: 'auctau' and 'tau' vectors are NULL")
  } else if(is.null(auctau)) {
    stop("Error in vzo: 'auctau' vector is NULL")
  } else if(is.null(tau)) {
    stop("Error in vzo: 'tau' vectors is NULL")
  } 

  if(is.na(auctau) || is.na(tau) || (0 %in% tau)){
    ca_v <- NA
  } else {
    ca_v <- auctau/tau
    ca_v <- replace(ca_v, is.infinite(ca_v), NA)
  }
  
  return(ca_v)
}