#' Last Measurable Plasma Concentration
#'
#' This function gets the last measurable plasma concentration that is obtained by the 
#' inspection of the data.
#' 
#' @details If all the concentrations are 0's then CLAST will return 'ND' for Not Determined. 
#' Also you must provide a valid sid with respect to the data.
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get clast for all the subjects)
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number 
#'  \item CLAST: last measurable plasma concentration
#' }
#' @examples 
#' ########## 
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##      0   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##    BLQ   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' clast()   
#' #No data found!
#' 
#' clast(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' clast(mod)  
#' #Please specify for which subject you want to get the CLAST for!
#' 
#' clast(mod, sid = "all")  
#' # SID  CLAST
#' #  30   2.47
#' #  31     ND
#' #  32   1.34
#' 
#' clast(mod, sid = 32)  
#' # SID  CLAST
#' #  32   1.34
#' 
#' clast(mod, sid = 10)  
#' Invaild subject ID! Subject ID not found in the data provided!
#' 
#' ##############
#' ## nca_data ##
#' ##############
#' 
#' mod2 <- model(nca_data, sid = "Subject", time = "Ntime", result = "Conc", dose = "Dose")
#' 
#' clast(mod2, "all")
#' #   SID CLAST
#' #1    1  3.28
#' #2    2  0.90
#' #3    3  1.05
#' #4    4  1.15
#' #5    5  1.57
#' #6    6  0.92
#' #7    7  1.15
#' #8    8  1.25
#' #9    9  1.12
#' #10  10  2.42
#' #11  11  0.00
#' #12  12  1.17
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' }
#' @export
clast_i <- function(data = NULL, map = NULL, sid = list(), interval = 0){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  if(!(is.numeric(interval))){
    stop("Invalid interval input! Please provide a numeric value for the interval")
  }
  
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  
  #data_data <- na.omit(data_data)
  clast_df <- data.frame(matrix(ncol = 3, nrow = 0))
  names(clast_df) <- c("SDEID", "CLAST", "INTERVAL")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  
  if(!is.null(sid)){
    if(tolower(sid) == 'all' || (typeof(sid) == 'list' && length(sid) == 0)){
      for(i in 1:length(unique(data_data[,map_data$SDEID]))){
        tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        if(interval > max(tmp[,map_data$NOMTIME])){
          stop("Interval provided is greater than maximum time!")
        }
        if(interval == 0) {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        } else {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
        }
        
        t_max <- max(tmp_df[,map_data$NOMTIME], na.rm = TRUE)
        c_last <- tmp_df[tmp_df[,map_data$NOMTIME] == t_max, map_data$CONC] 
        if(c_last == 0 || is.na(c_last)){  
          clast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval)  
        } else {
          clast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], c_last, interval)
        }
      }
      return(clast_df)
    } else {
      if(typeof(sid) == "list" && !any(!sid %in% data_data[,map_data$SDEID])) {
        data_data <- subset(data_data, data_data[,map_data$SDEID] %in% sid)
        for(i in 1:length(unique(data_data[,map_data$SDEID]))){
          tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          if(interval > max(tmp[,map_data$NOMTIME])){
            stop("Interval provided is greater than maximum time!")
          }
          if(interval == 0) {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          } else {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
          }
          
          t_max <- max(tmp_df[,map_data$NOMTIME], na.rm = TRUE)
          c_last <- tmp_df[tmp_df[,map_data$NOMTIME] == t_max, map_data$CONC] 
          if(c_last == 0 || is.na(c_last)){  
            clast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval)  
          } else {
            clast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], c_last, interval)
          }
        }
        return(clast_df)
      } else {
        stop("Values provided via 'sid' are not present in the dataset provided via 'data'")
      }
    } 
  } else {
    stop("Invalid value provided for 'sid'! Please provide a valid value for the 'sid' parameter")
  }
}