#' Maximum Observed Concentration
#'
#' This function gets the maxiumum observed concentration that is obtained by the inspection of the data.
#' It is designed as the first occurance within a dosing interval. In the case of multiple dosing, CMAXi 
#' is obtained by inspection of the data during each dosing interval i.
#'
#' @details If all the concentrations are 0's then CMAXi will be 0. Also the interval must be in the
#' range of the times listed in the data. And also you must provide a valid sid with respect to the data. \cr \cr
#' \strong{Equation} \cr
#' If the user selects the option to have dose normalized CMAX_i then the following equation is applied: \cr 
#' \figure{auc_dn_cmax.png} \cr 
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get cmax for all the subjects)
#' @param interval The endpoint of an dosing interval (if not provided then it will use the entire time interval)
#' @param dose_normalize The option to dose normalize the CMAX_i (default is 'FALSE')
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item CMAX: maximum observed concentration
#'  \item INTERVAL: endpoint of the dosing interval
#'  \item DOSE_NORM: whether the CMAX_i represented is dose normalized
#' }
#' 
#' @examples 
#' ##########
#' ## Data ##
#' ###########################################
#' ##  SID  ##  TIME  ##  RESULT  ##  DOSE  ##
#' ###########################################
#' ##   30  ##    0   ##   2.89   ##     2  ##
#' ##   30  ##    1   ##   2.49   ##     2  ##
#' ##   30  ##    2   ##   2.47   ##     2  ##
#' ##   31  ##    0   ##      0   ##     2  ##
#' ##   31  ##    1   ##      0   ##     2  ##
#' ##   31  ##    2   ##      0   ##     2  ##
#' ##   32  ##    0   ##   1.19   ##     2  ##
#' ##   32  ##    1   ##   1.23   ##     2  ##
#' ##   32  ##    2   ##   1.34   ##     2  ##
#' ##   32  ##    4   ##   1.32   ##     2  ##
#' ###########################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' cmax_i()   
#' #No data found!
#' 
#' cmax_i(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' cmax_i(mod)  
#' #Please specify for which subject you want to get the CMAXi for!
#' 
#' cmax_i(mod, sid = "all")  
#' # SID  CMAX  INTERVAL DOSE_NORM
#' #  30  2.89         0     FALSE
#' #  31     0         0     FALSE
#' #  32  1.34         0     FALSE
#' 
#' cmax_i(mod, sid = 30)  
#' # SID  CMAX  INTERVAL DOSE_NORM
#' #  30  2.89         0     FALSE
#' 
#' cmax_i(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' cmax_i(mod, sid = 31, interval = -1)
#' #Interval provided is less than zero!
#' 
#' cmax_i(mod, sid = 31, interval = 4)
#' #Interval provided is greater than maximum time!
#' 
#' cmax_i(mod, sid = 32, interval = 1)
#' # SID  CMAX  INTERVAL DOSE_NORM
#' #  32  1.23         1     FALSE
#' 
#' cmax_i(mod, sid = "all", interval = 4)
#' #Interval provided is greater than maximum time!
#' 
#' cmax_i(mod4, "all", interval = 1, dose_normalize = TRUE)
#' SID  CMAX INTERVAL DOSE_NORM
#'  30 1.245        1      TRUE
#'  31   0.5        1      TRUE
#'  32 0.615        1      TRUE
#'  
#' ##############
#' ## nca_data ##
#' ##############
#' 
#' mod5 <- model(nca_data, sid = "Subject", time = "Ntime", result = "Conc", dose = "Dose")
#' 
#' cmax_i(mod5, "all")
#' #   SID  CMAX INTERVAL DOSE_NORM
#' #1    1  10.5        0     FALSE
#' #2    2  8.33        0     FALSE
#' #3    3   8.2        0     FALSE
#' #4    4   8.6        0     FALSE
#' #5    5  11.4        0     FALSE
#' #6    6  6.44        0     FALSE
#' #7    7  7.09        0     FALSE
#' #8    8  7.56        0     FALSE
#' #9    9  9.03        0     FALSE
#' #10  10 10.21        0     FALSE
#' #11  11     8        0     FALSE
#' #12  12  9.75        0     FALSE
#' 
#' cmax_i(mod5, "all", dose_normalize = TRUE)
#' #   SID             CMAX INTERVAL DOSE_NORM
#' #1    1 2.61194029850746        0      TRUE
#' #2    2 2.07213930348259        0      TRUE
#' #3    3 2.03980099502488        0      TRUE
#' #4    4 2.13930348258706        0      TRUE
#' #5    5 2.83582089552239        0      TRUE
#' #6    6 1.60199004975124        0      TRUE
#' #7    7  1.7636815920398        0      TRUE
#' #8    8 1.88059701492537        0      TRUE
#' #9    9 2.24626865671642        0      TRUE
#' #10  10 2.53980099502488        0      TRUE
#' #11  11 1.99004975124378        0      TRUE
#' #12  12 2.42537313432836        0      TRUE
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' }
#' @export
cmax_i <- function(data = NULL, map = NULL, sid = list(), interval = 0, dose_normalize = FALSE){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  if(!(dose_normalize == TRUE || dose_normalize == FALSE)){
    stop("Invalid dose normalize input! Please provide either 'TRUE' or 'FALSE'")
  }
  if(!(is.numeric(interval))){
    stop("Invalid interval input! Please provide a numeric value for the interval")
  }
  
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  if(isTRUE(dose_normalize)){
    if(!("DOSE" %in% names(map_data))){
      stop("Dataset provided via 'map' does not contain the 'DOSE' column")
    }
    if(!(map_data$DOSE %in% names(data_data))){
      stop("'DOSE' value provided via 'map' are not present in the dataset provided via 'data'")
    }
  }

  #data_data <- na.omit(data_data)
  cmax_df <- data.frame(matrix(ncol = 4, nrow = 0))
  names(cmax_df) <- c("SDEID", "CMAX", "INTERVAL", "DOSE_NORMALIZE")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  
  if(!is.null(sid)){
    if(tolower(sid) == 'all' || (typeof(sid) == 'list' && length(sid) == 0)){
      for(i in 1:length(unique(data_data[,map_data$SDEID]))){
        tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        if(interval > max(tmp[,map_data$NOMTIME])){
          stop("Interval provided is greater than maximum time!")
        }
        if(interval == 0) {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        } else {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
          
        }
        c_max <- max(tmp_df[,map_data$CONC], na.rm = TRUE) 
        if(isTRUE(dose_normalize)){  
          dose_amt <- unique(data_data[,map_data$DOSE])[1]
          if(is.na(dose_amt) || dose_amt <= 0){
            cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize))  
          } else {
            if(is.infinite(c_max)){
              cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize)) 
            } else {
              tmp <- c_max/dose_amt
              cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], tmp, interval, as.character(dose_normalize))  
            }
          }
        } else {
          if(is.infinite(c_max)){
            cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize)) 
          } else {
            cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], c_max, interval, as.character(dose_normalize))
          }
        }
      }
      return(cmax_df)
    } else {
      if(typeof(sid) == "list" && !any(!sid %in% data_data[,map_data$SDEID])) {
        data_data <- subset(data_data, data_data[,map_data$SDEID] %in% sid)
        for(i in 1:length(unique(data_data[,map_data$SDEID]))){
          tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          if(interval > max(tmp[,map_data$NOMTIME])){
            stop("Interval provided is greater than maximum time!")
          }
          if(interval == 0) {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          } else {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
            
          }
          c_max <- max(tmp_df[,map_data$CONC], na.rm = TRUE) 
          if(isTRUE(dose_normalize)){  
            dose_amt <- unique(data_data[,map_data$DOSE])[1]
            if(is.na(dose_amt) || dose_amt <= 0){
              cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize))  
            } else {
              if(is.infinite(c_max)){
                cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize)) 
              } else {
                tmp <- c_max/dose_amt
                cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], tmp, interval, as.character(dose_normalize))  
              }
            }
          } else {
            if(is.infinite(c_max)){
              cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval, as.character(dose_normalize)) 
            } else {
              cmax_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], c_max, interval, as.character(dose_normalize))
            }
          }
        }
        return(cmax_df)
      } else {
        stop("Values provided via 'sid' are not present in the dataset provided via 'data'")
      }
    } 
  } else {
    stop("Invalid value provided for 'sid'! Please provide a valid value for the 'sid' parameter")
  }
}