#' Terminal or Elimination phase rate constant
#'
#' This function gets the terminal or elimination phase rate constant, which is described as the absolute
#' value of the slope of a least-squares linear regression during the terminal phase of the natural-logarithm
#' (ln) transformed concentration-time profile.
#' 
#' @aliases kel_tmlo kel_tmhi kel_nopt
#' 
#' @details
#' \strong{First calculate slope} \cr  
#' \figure{kel_eq1.png} \cr
#' \figure{kel_eq2.png} \cr
#' \figure{kel_eq3.png} \cr
#' \eqn{S = Slope} \cr
#' \eqn{C_{i} = i^{th} concentration}{Ci = ith concentration} \cr
#' \eqn{T_{i} = i^{th} time}{Ti = ith time} \cr
#' \eqn{n = the number of data points} \cr \cr
#' \strong{Terminal log-linear phase} = The phase in the natural-log transformed concentration-time profile selected
#' by user at the time of primary parameter computaitons via interactive concentration-time plots(refer to KEL
#' tab on the front end) \cr \cr  
#' Set time of last dose TDOSE to 0 and shift T accordingly in calculation of KEL. This impacts the C0 the intercept
#' used in other paramerter calculations AUCINF \cr \cr
#' \strong{Equation for KEL}\cr \eqn{KEL = S x -1} \cr
#' 
#' @section Note:
#' If concentrations are less than or equal to zero or 'NA' for a data point, that data point is not used
#' in calculations. There needs to be atleast 2 data points in the data. If KEL is less than 0 then the function
#' will return 'ND' for Not Determined. And also you must provide a valid sid with respect to the data. 
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item KEL: maximum observed concentration
#'  \item TMLO: intial timepoint used in the calculation of KEL
#'  \item TMHI: final timepoint used in the calculation of KEL
#'  \item NOPT: number of time points used in the calculation of KEL
#' }
#' @section Additional Details:
#' If KEL returns 'ND' or 'Not Determined' then TMHI and TMLO both are set to 'ND' as well. If TMLO is greater
#' than or equal to TMHI, then TMLO is set to 'ND. If TMHI is less than or equal to TMLO, then TMHI is set
#' to 'ND'.
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' kel()   
#' #No data found!
#' 
#' kel(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' kel(mod)  
#' #Please specify for which subject you want to get the KEL for!
#' 
#' kel(mod, sid = "all")  
#' # SID     KEL TMLO  TMHI  NOPT
#' #  30  0.0785    0     2     3
#' #  31      ND   ND    ND     1
#' #  32      ND   ND    ND     4
#' 
#' kel(mod, sid = 31)  
#' # SID KEL TMLO TMHI NOPT
#' #  31  ND  ND    ND   1
#' 
#' kel(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' }
#' @export
kel <- function(data = NULL, map = NULL){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  
  kel_df <- data.frame(matrix(ncol = 5, nrow = 0))
  names(kel_df) <- c("SDEID", "KEL", "KELTMLO", "KELTHMI", "KELNOPT")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  for(i in 1:length(unique(data_data[,map_data$SDEID]))){
    tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
    dftemp <- subset(tmp, tmp[,map_data$CONC] > 0)
    #print(dftemp)
    if(nrow(dftemp) > 1){
      row.names(dftemp) <- 1:nrow(dftemp)
      #print(dftemp)
      kel_tmlo <- min(dftemp[,map_data$NOMTIME])
      kel_tmhi <- max(dftemp[,map_data$NOMTIME])
      kel_nopt <- length(dftemp[,map_data$NOMTIME])
      if(kel_tmhi == kel_tmlo){
        kel_tmlo <- "ND"
        kel_tmhi <- "ND"
      }
      if(kel_tmlo > kel_tmhi){
        kel_tmlo <- "ND"
      }
      if(kel_tmhi < kel_tmlo){
        kel_tmhi <- "ND"
      }
      time <- (sum(dftemp[,map_data$NOMTIME])/nrow(dftemp))
      #print(paste0("Time:", time))
      conc <- (sum(sapply(dftemp[,map_data$CONC], function(x) {
        return(log(x))
      }))/nrow(dftemp))
      #print(paste0("Concentration:", conc))
      conc_ln <- sapply(dftemp[,map_data$CONC], function(x) {
        return(log(x))
      })
      #print(paste0("ln(Concentration):", conc_ln))
      slope_numer <- ((sum(sapply(dftemp[,map_data$NOMTIME], function(x){
        #print(conc_ln[as.numeric(row.names(dftemp[dftemp$TIME == x,]))])
        return(x*conc_ln[as.numeric(row.names(dftemp[dftemp[,map_data$NOMTIME] == x,]))])
      }))) - (nrow(dftemp)*time*conc))
      #print(paste0("Slope Numer:", slope_numer))
      slope_denom <- ((sum(sapply(dftemp[,map_data$NOMTIME], function(x){
        return(x*x)
      }))) - (nrow(dftemp)*(time*time)))
      #print(paste0("Slope Denom:", slope_denom))
      if(slope_numer == 0 && slope_denom == 0){
        slope = 0
      } else {
        slope = slope_numer/slope_denom 
      }
      #print(paste0("Slope:", slope))
      kel <- (slope*(-1))
      #print(paste0("Kel:", round(kel, 4)))
      
      if(kel <= 0){
        kel_tmlo <- "ND"
        kel_tmhi <- "ND"
        kel_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", kel_tmlo, kel_tmhi, kel_nopt)
      } else {
        kel_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], round(kel, 4), kel_tmlo, kel_tmhi, kel_nopt)
      }
    } else {
      kel_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", "ND", "ND", nrow(dftemp))
    }
  }
  
  return(kel_df)
}