#' Goodness of fit statistic for Terminal or Elimination phase rate constant
#'
#' This function gets the goodness of fit statistic (r^2) for the terminal phase rate constant (kel). 
#' This function also gets the goodness of fit statistic (r^2) for the terminal phase rate constant 
#' (kel) adjusted for the number of points used for the estimation of (kel)
#' 
#' @aliases kel_rsqa
#' 
#' @details
#' \strong{Equation} \cr  
#' \figure{kel_rsq0.png} \cr
#' \figure{kel_rsq1.png} \cr
#' \figure{kel_rsq2.png} \cr
#' \figure{kel_rsq3.png} \cr
#' \eqn{S = Slope} \cr
#' \eqn{C_{i} = Concentration at each point for a profile}{Ci = Concentration at each point for a profile} \cr
#' \eqn{T_{i} = Time at each point for a profile}{Ti = Time at each point for a profile} \cr
#' \eqn{N = Number of provided times/concentrations data points in a profile} \cr \cr
#' \strong{Note:} If curve stripping is checked then follow curve stripping logic before outputting KELRSQ value \cr
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item RSQ: Goodness of fit statistic for Terminal or Elimination phase rate constant
#'  \item RSQ_A: Goodness of fit statistic for Terminal or Elimination phase rate constant adjusted
#' }
#' @section Additional Details for RSQ_A:
#' \strong{Equation} \cr  
#' If the user wanted the adjusted r squared value: \cr
#' \figure{kel_rsqa.png} \cr
#' \eqn{r^{2} = Another primary parameter}{r^2 = Another primary parameter} \cr
#' \eqn{N = Number of provided times/concentrations data points in a profile} \cr \cr
#' \strong{Note:} This function call on kel() in order to generate the goodness of fir statistic \cr
#' 
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' kel_rsq()   
#' #No data found!
#' 
#' kel_rsq(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' kel_rsq(mod)  
#' #Please specify for which subject you want to get the KEL_RSQ for!
#' 
#' kel_rsq(mod, sid = "all")  
#' # SID      RSQ    RSQ_A
#' #  30  0.62158  0.24317
#' #  31       ND       ND
#' #  32       ND       ND
#' 
#' kel_rsq(mod, sid = 31)  
#' # SID   RSQ   RSQ_A
#' #  31    ND      ND
#' 
#' kel_rsq(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' } 
#' @export
kel_rsq <- function(data = NULL, map = NULL){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  
  kel_df <- kel(data = data, map = map)
  #print(kel_df)
  kelr_df <- data.frame(matrix(ncol = 4, nrow = 0))
  names(kelr_df) <- c("SDEID", "KELR", "KELRSQ", "KELSQADJ")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  for(i in 1:length(unique(data_data[,map_data$SDEID]))){
    kel_tmp <- kel_df[kel_df$SDEID == unique(data_data[,map_data$SDEID])[i],]
    #print(kel_tmp)
    tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
    dftemp <- subset(tmp, tmp[,map_data$CONC] > 0)
    #print(dftemp)
    if(nrow(dftemp) > 1){
      row.names(dftemp) <- 1:nrow(dftemp)
      #print(dftemp)
      conc_ln <- sapply(dftemp[,map_data$CONC], function(x) {
        return(log(x))
      })
      #print(paste0("ln(Concentration):", conc_ln))
      ssct_p1 <- sum(sapply(dftemp[,map_data$NOMTIME], function(x) { return(conc_ln[which(dftemp[,map_data$NOMTIME] == x)]*x) }))
      #print(paste0("ssct_p1:", ssct_p1))
      ssct_p2 <- ((sum(conc_ln)*sum(dftemp[,map_data$NOMTIME]))/nrow(dftemp))
      #print(paste0("ssct_p2:", ssct_p2))
      ssct <- ssct_p1 - ssct_p2
      sst <- (sum(sapply(dftemp[,map_data$NOMTIME], function(x){
        return(x*x)
      }))-((sum(dftemp[,map_data$NOMTIME])*sum(dftemp[,map_data$NOMTIME]))/nrow(dftemp)))
      #print(paste0("sst:", sst))
      ssc <- (sum(sapply(conc_ln, function(x) { 
        (x*x) 
      }))-((sum(conc_ln)*sum(conc_ln))/nrow(dftemp)))
      #print(paste0("ssc:", ssc))
      r_sq <- ((ssct*ssct)/(sst*ssc))
      kel_r <- r_sq
      kel_r_sq <- r_sq*r_sq
      #print(paste0("r_sq:", kel_r_sq))
      kel_r_sqa <- (1-(1-r_sq)*((nrow(dftemp)-1)/(nrow(dftemp)-2)))
      #print(paste0("r_sqa:", kel_r_sqa))
      if(kel_tmp$KEL <= 0 || kel_tmp$KEL == 'ND'){
        kelr_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", "ND", "ND")
      } else {
        kelr_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], kel_r, kel_r_sq, kel_r_sqa)
      }
      #print(kelr_df[i,])
    } else {
      kelr_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", "ND", "ND")
    }
  }
  
  return(kelr_df)
}

