#' The mean residence time (MRT) extrapolated to infinity for a substance administered by extravascular 
#' dosing, calculated using the observed value of the last non-zero concentration.
#'
#' Note that the parameter naming convention for Release 2 of the Computaton Engine Specifications 
#' referred to MRTEVIFO(i) as MRTOi for extravascular administration. This has been changed to MRTEVIFO(i) 
#' with Release 3 to distinguish between intra- and extravascular administration.\cr
#' 
#' @details
#' \strong{Single Dose Equation:}
#' \strong{For Model M2}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{mrt_ivifo_1.png} \cr
#'  }
#' }
#' \strong{For Model M3}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{mrt_ivifo_2.png} \cr
#'  }
#' }
#' \strong{Steady-State Equation:}
#' \strong{For Model M2}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{aumc_XpctP1.png} \cr
#'  }
#' }
#' \strong{For Model M3}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{aumc_XpctP1.png} \cr
#'  }
#' }
#' \eqn{AUMCINFO = Area under the first moment curve from zero time to infinity (Observed)} \cr  
#' \eqn{AUCINFO = Area under the concentration versus time curve from zero time to infinity (Observed)} \cr   
#' \eqn{AUMCTAUi = Area under the first moment curve from zero time until the end of the ith dosing interval} \cr  
#' \eqn{AUCTAUi = Area under the concentration versus time curve from zero time until the end of the ith dosing interval} \cr   
#' \eqn{TAUi = ith Dosing interval i refers to the value of NDOSEI} \cr  
#' 
#' @section Additional Details:
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @param method The method that will be used to calculate AUC (use either 1, 2, 3, or 4)\cr
#' 
#' \enumerate{
#' \item Linear-Log Trapazoidal Rule (default)
#' \item Linear Trapazoidal Rule 
#' \item Log Trapazoidal Rule 
#' \item Linear Up - Log DownTrapazoidal Rule 
#' } 
#' Note: check 'Methods' section below for more details \cr
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item AUMC_PER: percentage of area under the curve
#'  \item METHOD: method used to calculate AUC
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' aumc_XpctP()   
#' #No data found!
#' 
#' aumc_XpctP(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' aumc_XpctP(mod)  
#' #Please specify for which subject you want to get the AUMC_XPCTP for!
#' 
#' aumc_XpctP(mod, sid = "all") 
#' #  SID              AUC     METHOD
#' #   30 4.94993257703106 Linear-Log
#' #   31                1 Linear-Log
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 32)  
#' #  SID              AUC     METHOD
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' aumc_XpctP(mod, sid = 31, method = 5)
#' #Invalid method number! Please provide a valid value for method!
#' 
#' @author
#' \itemize{
#'  \item Ronish Desai: \email{rbdesai@@rudraya.com} 
#' }
#' Other contributors: \cr
#' \itemize{
#'  \item Rudraya Corporation: \url{http://rudraya.com}
#' }
#' \figure{rudraya.png} 
#' @export
mrt_ivif_o <- function(conc = NULL, time = NULL, method = 1, model = "M2", parameter = "SD"){
  if(is.null(conc) && is.null(time)){
    stop("Error in mrt_ivif_o: 'conc' and 'time' vectors are NULL")
  } else if(is.null(conc)) {
    stop("Error in mrt_ivif_o: 'conc' vector is NULL")
  } else if(is.null(time)) {
    stop("Error in mrt_ivif_o: 'time' vectors is NULL")
  }
  
  if(!(is.numeric(conc) && is.vector(conc)) ){
    stop("Error in mrt_ivif_o: 'conc' is not a numeric vector")
  }
  if(!(is.numeric(time) && is.vector(time)) ){
    stop("Error in mrt_ivif_o: 'time' is not a numeric vector")
  }
  if(length(time) != length(conc)){
    stop("Error in mrt_ivif_o: length of 'time' and 'conc' vectors are not equal")
  }
  if(method != 1 && method != 2 && method != 3 && method != 4){
    stop("Error in mrt_ivif_o: the value provided for 'method' is not correct")
  }
  if(model != "M2" && model != "m2" && model != "M3" && model != "m3"){
    stop("Error in mrt_ivif_o: the value provided for 'model' is not correct")
  }
  if(tolower(parameter) != "sd" && tolower(parameter) != "ss"){
    stop("Error in mrt_ivif_o: the value provided for 'parameter' is not correct")
  }
  
  mrtivifo <- NA
  if(model == "M2" || model == "m2") {
    if(tolower(parameter) == "sd") {
      auc_info <- auc_inf_o(conc = conc, time = time, method = method)
      aumc_info <- aumc_inf_o(conc = conc, time = time, method = method) 
      
      if(auc_info <= 0 || aumc_info < 0 || is.na(auc_info) || is.na(aumc_info)){
        mrtivifo <- NA
      } else {
        mrtivifo <- aumc_info/auc_info
      }
    } else if(tolower(parameter) == "ss") {
      
    }
  } else if(model == "M3" || model == "m3") {
    
  }
  
  return(mrtivifo)
}