#' Mean residence time from the time of dosing to the last measurable concentration.
#' 
#' @details
#' \strong{Single Dose Equation:}
#' \strong{For Model M1}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{aumc_XpctP1.png} \cr
#'  }
#' }
#' \strong{Steady-State Equation:}
#' \strong{For Model M1}
#' \enumerate{
#'  \tabular{rl}{
#'   \tab \figure{aumc_XpctP1.png} \cr
#'  }
#' }
#' \eqn{AUMClast = Aea under the first moment curve from zero time until the last measurable concentration} \cr  
#' \eqn{AUClast = Area under the concentration versus time curve from zero time until the time (Tlast) of the last measurable concentration (CLASTi} \cr   
#' \eqn{DOF = duration of infusion, used for constant infusion models} \cr  
#' 
#' @section Additional Details:
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get kel for all the subjects)
#' @param method The method that will be used to calculate AUC (use either 1, 2, 3, or 4)\cr
#' 
#' \enumerate{
#' \item Linear-Log Trapazoidal Rule (default)
#' \item Linear Trapazoidal Rule 
#' \item Log Trapazoidal Rule 
#' \item Linear Up - Log DownTrapazoidal Rule 
#' } 
#' Note: check 'Methods' section below for more details \cr
#' 
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item AUMC_PER: percentage of area under the curve
#'  \item METHOD: method used to calculate AUC
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##   1.00   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' aumc_XpctP()   
#' #No data found!
#' 
#' aumc_XpctP(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' aumc_XpctP(mod)  
#' #Please specify for which subject you want to get the AUMC_XPCTP for!
#' 
#' aumc_XpctP(mod, sid = "all") 
#' #  SID              AUC     METHOD
#' #   30 4.94993257703106 Linear-Log
#' #   31                1 Linear-Log
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 32)  
#' #  SID              AUC     METHOD
#' #   32 5.15416479501756 Linear-Log
#' 
#' aumc_XpctP(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' aumc_XpctP(mod, sid = 31, method = 5)
#' #Invalid method number! Please provide a valid value for method!
#' 
#' @author
#' \itemize{
#'  \item Ronish Desai: \email{rbdesai@@rudraya.com} 
#' }
#' Other contributors: \cr
#' \itemize{
#'  \item Rudraya Corporation: \url{http://rudraya.com}
#' }
#' \figure{rudraya.png} 
#' @export
mrt_last <- function(conc = NULL, time = NULL, method = 1, model = "M1"){
  if(is.null(conc) && is.null(time)){
    stop("Error in mrt_evif_o: 'conc' and 'time' vectors are NULL")
  } else if(is.null(conc)) {
    stop("Error in mrt_evif_o: 'conc' vector is NULL")
  } else if(is.null(time)) {
    stop("Error in mrt_evif_o: 'time' vectors is NULL")
  }
  
  if(!(is.numeric(conc) && is.vector(conc)) ){
    stop("Error in mrt_evif_o: 'conc' is not a numeric vector")
  }
  if(!(is.numeric(time) && is.vector(time)) ){
    stop("Error in mrt_evif_o: 'time' is not a numeric vector")
  }
  if(length(time) != length(conc)){
    stop("Error in mrt_evif_o: length of 'time' and 'conc' vectors are not equal")
  }
  if(method != 1 && method != 2 && method != 3 && method != 4){
    stop("Error in aumc_XpctP: the value provided for 'method' is not correct")
  }
  if(model != "M1" && model != "m1" && model != "M2" && model != "m2" && model != "M3" && model != "m2"){
    stop("Error in mrt_evif_p: the value provided for 'model' is not correct")
  }
  
  mrtlast <- NA
  if(model == "M1" || model == "m1" || model == "M2" || model == "m2" ) {
    auclast <- auc_last(conc = conc, time = time, method = method)
    aumclast <- aumc_last(conc = conc, time = time, method = method) 
    
    if(auclast <= 0 || aumclast < 0 || is.na(auclast) || is.na(aumclast)){
      mrtlast <- NA
    } else {
      mrtlast <- aumclast/auclast
    }
  } else if(model == "M3" || model == "m3") {
    auclast <- auc_last(conc = conc, time = time, method = method)
    aumclast <- aumc_last(conc = conc, time = time, method = method) 
    dof <- 1
    
    if(auclast <= 0 || aumclast < 0 || is.na(auclast) || is.na(aumclast)){
      mrtlast <- NA
    } else {
      mrtlast <- aumclast/auclast - dof/2
    }
  }
  
  return(mrtlast)
}