#' Time at Last Measurable Plasma Concentration
#'
#' This function gets the time of last measurable plasma concentration that is obtained by the 
#' inspection of the data.
#' 
#' @details If all the concentrations are 0's then TLAST will return 'ND' for Not Determined. 
#' You must provide a valid sid with respect to the data.
#' 
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get tlast for all the subjects)
#' @param include To include zero's within the calculation for TLAST
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item TLAST: time at last mesuarable plasma concentration
#' }
#' @examples 
#' ########## 
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##      0   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##      0   ##
#' ##   32  ##    4   ##    BLQ   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' tlast()   
#' #No data found!
#' 
#' tlast(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' clast(mod)  
#' #Please specify for which subject you want to get the TLAST for!
#' 
#' tlast(mod, sid = "all")  
#' # SID  TMAX
#' #  30     2
#' #  31    ND
#' #  32     2
#' 
#' tlast(mod, sid = 32)  
#' # SID  TMAX
#' #  32     2
#' 
#' tlast(mod, sid = 32, include = FALSE)  
#' # SID  TMAX
#' #  32     1
#' 
#' tlast(mod, sid = 10)  
#' Invaild subject ID! Subject ID not found in the data provided!
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' }
#' @export
tlast <- function(data = NULL, map = NULL, sid = list()){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  
  #data_data <- na.omit(data_data)
  tlast_df <- data.frame(matrix(ncol = 2, nrow = 0))
  names(tlast_df) <- c("SDEID", "TLAST")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  
  if(!is.null(sid)){
    if(tolower(sid) == 'all' || (typeof(sid) == 'list' && length(sid) == 0)){
      for(i in 1:length(unique(data_data[,map_data$SDEID]))){
        tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        
        max_time <- max(tmp_df[,map_data$NOMTIME], na.rm = TRUE) 
        c_max <- max(tmp_df[,map_data$CONC], na.rm = TRUE) 
        if(c_max == 0 || is.na(c_max) || is.infinite(c_max)){  
          tlast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND")  
        } else  {
          tlast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], max_time)
        }
      }
      return(tlast_df)
    } else {
      if(typeof(sid) == "list" && !any(!sid %in% data_data[,map_data$SDEID])) {
        data_data <- subset(data_data, data_data[,map_data$SDEID] %in% sid)
        for(i in 1:length(unique(data_data[,map_data$SDEID]))){
          tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          
          max_time <- max(tmp_df[,map_data$NOMTIME], na.rm = TRUE) 
          c_max <- max(tmp_df[,map_data$CONC], na.rm = TRUE) 
          if(c_max == 0 || is.na(c_max) || is.infinite(c_max)){  
            tlast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND")  
          } else  {
            tlast_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], max_time)
          }
        }
        return(tlast_df)
      } else {
        stop("Values provided via 'sid' are not present in the dataset provided via 'data'")
      }
    } 
  } else {
    stop("Invalid value provided for 'sid'! Please provide a valid value for the 'sid' parameter")
  }
}