#' Time at Minimum Observed Concentration
#'
#' This function gets the first time at which CMINi is observed within the dosing interval and
#' is obtained by the inspection of the data. In the case of multiple dosing, TMINi 
#' is obtained by inspection of the data during each dosing interval i. 
#' 
#' @details If all the concentrations are 0's then TMINi will return 'ND' for Not Determined. 
#' Also if the interval provided is less than 0 then TMINi will return 'ND' for Not Determined. 
#' And also you must provide a valid sid with respect to the data.
#'
#' @param data The model data that was generated by \code{\link{model}} 
#' @param sid The subject ID (either can be the id number or 'all' to get tmin for all the subjects)
#' @param interval The endpoint of an dosing interval (if not provided then it will use the entire time interval)
#' @section Returns:
#' \strong{Dataset} \cr 
#' \itemize{
#'  \item SID: subject identification number
#'  \item TMIN: time at minimum observed concentration
#'  \item INTERVAL: endpoint of the dosing interval
#' }
#' @examples 
#' ##########
#' ## Data ##
#' #################################
#' ##  SID  ##  TIME  ##  RESULT  ##
#' #################################
#' ##   30  ##    0   ##   2.89   ##
#' ##   30  ##    1   ##   2.49   ##
#' ##   30  ##    2   ##   2.47   ##
#' ##   31  ##    0   ##      0   ##
#' ##   31  ##    1   ##      0   ##
#' ##   31  ##    2   ##      0   ##
#' ##   32  ##    0   ##   1.19   ##
#' ##   32  ##    1   ##   1.23   ##
#' ##   32  ##    2   ##   1.34   ##
#' ##   32  ##    4   ##   1.32   ##
#' #################################
#' 
#' data <- data.frame(
#'     SID = ...,
#'     TIME = ...,
#'     RESULT = ...
#' )
#' #Same data as above, just represented as a dataframe
#' 
#' tmin_i()   
#' #No data found!
#' 
#' tmin_i(data)  
#' #Object not of class NCA
#' 
#' mod <- model("~/data.csv")  
#' #Creates an NCA object with data represented in 'data' above
#' tmin_i(mod)  
#' #Please specify for which subject you want to get the TMINi for!
#' 
#' tmin_i(mod, sid = "all")  
#' # SID  TMAX  INTERVAL
#' #  30     2         0
#' #  31    ND         0
#' #  32     0         0
#' 
#' tmin_i(mod, sid = 31)  
#' # SID  TMAX  INTERVAL
#' #  31    ND         0
#' 
#' tmin_i(mod, sid = 10)  
#' #Invaild subject ID! Subject ID not found in the data provided!
#' 
#' tmin_i(mod, sid = 31, interval = -1)
#' #Interval provided is less than zero!
#' 
#' tmin_i(mod, sid = 31, interval = 4)
#' #Interval provided is greater than maximum time!
#' 
#' tmin_i(mod, sid = 30, interval = 1)
#' # SID  TMAX  INTERVAL
#' #  30     1         1
#' 
#' tmin_i(mod, sid = "all", interval = 4)
#' #Interval provided is greater than maximum time!
#' 
#' @author
#' \itemize{
#'  \item Kevin McConnell
#' }
#' @export
tmin_i <- function(data = NULL, map = NULL, sid = list(), interval = 0){
  if(is.null(data)){
    stop("Please provide a valid path for the 'data' parameter")
  } else {
    if(is.data.frame(data)){
      data_data <- data
    } else {
      if(file.exists(data)){
        data_data <- read.csv(file = data)
      } else {
        stop("Invalid path provided for 'data'! Please provide a valid path for the 'data' parameter")
      } 
    }
  }
  if(is.null(map)){
    stop("Please provide a valid path for the 'map' parameter")
  } else {
    if(is.data.frame(map)){
      map_data <- as.data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
    } else {
      if(file.exists(map)){
        map_data <- read.csv(file = map, stringsAsFactors = FALSE)
      } else {
        stop("Invalid path provided for 'map'! Please provide a valid path for the 'map' parameter")
      }
    }
  }
  if(!(is.numeric(interval))){
    stop("Invalid interval input! Please provide a numeric value for the interval")
  }
  
  if(!("SDEID" %in% names(map_data) && "NOMTIME" %in% names(map_data) && "CONC" %in% names(map_data))){
    stop("Dataset provided via 'map' does not contain the required columns")
  }
  if(!(map_data$SDEID %in% names(data_data) && map_data$NOMTIME %in% names(data_data) && map_data$CONC %in% names(data_data))){
    stop("Values provided via 'map' are not present in the dataset provided via 'data'")
  }
  
  #data_data <- na.omit(data_data)
  tmin_df <- data.frame(matrix(ncol = 3, nrow = 0))
  names(tmin_df) <- c("SDEID", "TMIN", "INTERVAL")
  data_data[,map_data$CONC] <- as.numeric(as.character(data_data[,map_data$CONC]))
  data_data[,map_data$NOMTIME] <- as.numeric(as.character(data_data[,map_data$NOMTIME]))
  
  if(!is.null(sid)){
    if(tolower(sid) == 'all' || (typeof(sid) == 'list' && length(sid) == 0)){
      for(i in 1:length(unique(data_data[,map_data$SDEID]))){
        tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        if(interval > max(tmp[,map_data$NOMTIME])){
          stop("Interval provided is greater than maximum time!")
        }
        if(interval == 0) {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
        } else {
          tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
        }
        c_min <- min(tmp_df[,map_data$CONC], na.rm = TRUE) 
        t_min <- min(tmp_df[tmp_df[,map_data$CONC] == c_min, map_data$NOMTIME], na.rm = TRUE) 
        if(c_min == 0 || is.na(c_min) || is.infinite(c_min)){  
          tmin_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval)  
        } else  {
          tmin_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], t_min, interval)
        }
      }
      return(tmin_df)
    } else {
      if(typeof(sid) == "list" && !any(!sid %in% data_data[,map_data$SDEID])) {
        data_data <- subset(data_data, data_data[,map_data$SDEID] %in% sid)
        for(i in 1:length(unique(data_data[,map_data$SDEID]))){
          tmp <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          if(interval > max(tmp[,map_data$NOMTIME])){
            stop("Interval provided is greater than maximum time!")
          }
          if(interval == 0) {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i],]
          } else {
            tmp_df <- data_data[data_data[,map_data$SDEID] == unique(data_data[,map_data$SDEID])[i] & data_data[,map_data$NOMTIME] %in% 0:interval,]
          }
          c_min <- min(tmp_df[,map_data$CONC], na.rm = TRUE) 
          t_min <- min(tmp_df[tmp_df[,map_data$CONC] == c_min, map_data$NOMTIME], na.rm = TRUE) 
          if(c_min == 0 || is.na(c_min)){  
            tmin_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], "ND", interval)  
          } else  {
            tmin_df[i,] <- c(unique(data_data[,map_data$SDEID])[i], t_min, interval)
          }
        }
        return(tmin_df)
      } else {
        stop("Values provided via 'sid' are not present in the dataset provided via 'data'")
      }
    } 
  } else {
    stop("Invalid value provided for 'sid'! Please provide a valid value for the 'sid' parameter")
  }
}